

TARGET_EXT=cpp

TYPE=bin

MODULE_LOAD=PCM PTHREAD
MACHINE_NAME=EXCESS
#PCM_SRC=/home/lu/Documents/Software/PCM/2.8/IntelPerformanceCounterMonitorV2.8
#EF=$(PCM_SRC)/cpucounters.cpp $(PCM_SRC)/msr.cpp $(PCM_SRC)/pci.cpp $(PCM_SRC)/client_bw.cpp
RP=sudo

NO_CPPCHECK:=true

NO_WARNINGS:=true

CXX_CFLAGS+=-I . -g3

include MakefileCommon
